version: "3"
services:
    mautic:
      restart: always
      image: "mautic/mautic-v3-${MAUTIC_HTTP_SERVER}"
      ports: 
        - ${MAUTIC_HTTP_PORT}:80
      volumes:
        - mautic_data:/var/www/html
      environment:
        - MAUTIC_DB_HOST=mysql
        - MAUTIC_DB_USER=${DB_USER}
        - MAUTIC_DB_PASSWORD=${DB_PASSWORD}
        - MAUTIC_DB_NAME=${DB_NAME}
        - MAUTIC_RUN_CRON_JOBS=${MAUTIC_RUN_CRON}
    
    mysql:
      image: 'deckapp/mysql:v10.1.19'
      environment:
        - "MYSQL_DATABASE=${DB_NAME}"
        - "MYSQL_USER=${DB_USER}"
        - "MYSQL_PASSWORD=${DB_PASSWORD}"
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ./mysql:/etc/mysql/
      ports:
        - ${MYSQL_PORT}:3306
    
volumes:
  mautic_data:
    driver: "${VOLUMES_DRIVER}"
