version: '3'
services:
    mautic:
      restart: always
      build: 
        context: './mautic'
        dockerfile: 'Dockerfile-${MAUTIC_HTTP_SERVER}'
      ports: 
        - ${MAUTIC_HTTP_PORT}:80
      volumes:
        - mautic_data:/var/www/html
      environment:
        - MAUTIC_DB_HOST=mysql
        - MAUTIC_DB_USER=${DB_USER}
        - MAUTIC_DB_PASSWORD=${DB_PASSWORD}
        - MAUTIC_DB_NAME=${DB_NAME}
        - MAUTIC_RUN_CRON_JOBS=${MAUTIC_RUN_CRON}
        - MAUTIC_HTTP_SERVERP=${MAUTIC_HTTP_SERVER}
    
    mysql:
      build:
        context: './mysql'
      environment:
        - 'MYSQL_DATABASE=${DB_NAME}'
        - 'MYSQL_USER=${DB_USER}'
        - 'MYSQL_PASSWORD=${DB_PASSWORD}'
        - 'MYSQL_ROOT_PASSWORD=${DB_root_PASSWORD}'
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      ports:
        - ${MYSQL_PORT}:3306
    
volumes:
  mautic_data:
    driver: '${VOLUMES_DRIVER}'
