#User defined
user:
  back_end:
    label:
      Backend
    hint:
      Select a backend from the list above
    type:
      select
    values:
      - apache
      - nginx
    target:
      BACK_END
  php_version:
    label:
      PHP version
    hint:
      Select a PHP version from the list above
    type:
      select
    values:
      - 7.4
      - "8.0"
    target:
      PHP_VERSION

  php_error_reporting:
    label:
      Enable PHP error reporting?
    type:
      checkbox
    hint: Check the box to display PHP errors 
    target:
      DISPLAY_PHPERROR
  php_xdebug:
    label:
      Enable PHP extension XDEBUG?
    type:
      checkbox
    hint: Check the box to display extension xdebug
    target:
      XDEBUG
    
  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION

  # customize_server_root_path:
  #   label:
  #     Server root
  #   type:
  #     input
  #   values:
  #     /var/www
  #   hint:
  #     Server document root
  #   target:
      # SERVER_ROOT

#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      MAUTIC_HOST_HTTP_PORT
    others:
      - MYSQL_PORT
      - PMA_PORT

