name: mautic

on:
  schedule:
  - cron:  '30 5 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nginx-php8-mautic-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image nginx, php 8.0 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "8.0"
        BACK_END: nginx
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www/
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic_mautic_1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic_mautic_1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic_mautic_1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic_mautic_1 composer
    - name: Folder check
      run:  docker exec mautic_mautic_1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
    - name: Root path check
      run: |
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/nginx/conf.d/default.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/nginx/conf.d/default.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  Nginx-php8-mautic-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image nginx, php 8.0 and Mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "8.0"
        BACK_END: nginx
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic-mautic-1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic-mautic-1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic-mautic-1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic-mautic-1 composer
    - name: Folder check
      run:  docker exec mautic-mautic-1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
    - name: Root path check
      run: |
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/nginx/conf.d/default.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/nginx/conf.d/default.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  
  Nginx-php7-mautic-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image nginx, php 7.4 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "7.4"
        BACK_END: nginx
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www/
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic_mautic_1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic_mautic_1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic_mautic_1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic_mautic_1 composer
    - name: Folder check
      run:  docker exec mautic_mautic_1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
    - name: Root path check
      run: |
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/nginx/conf.d/default.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/nginx/conf.d/default.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  Nginx-php7-mautic-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image nginx, php 7.4 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "7.4"
        BACK_END: nginx
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic-mautic-1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic-mautic-1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic-mautic-1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic-mautic-1 composer
    - name: Folder check
      run:  docker exec mautic-mautic-1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
    - name: Root path check
      run: |
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/nginx/conf.d/default.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/nginx/conf.d/default.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic

   
  Apache-php8-mautic-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image apache, php 8.0 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "8.0"
        BACK_END: apache
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www/
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic_mautic_1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic_mautic_1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic_mautic_1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic_mautic_1 composer
    - name: Folder check
      run:  docker exec mautic_mautic_1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic_mautic_1 chown -R apache:apache /var/www/
    - name: Root path check
      run: |
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/apache2/httpd.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/apache2/httpd.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  Apache-php8-mautic-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image apache, php 8.0 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "8.0"
        BACK_END: apache
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic-mautic-1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic-mautic-1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic-mautic-1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic-mautic-1 composer
    - name: Folder check
      run:  docker exec mautic-mautic-1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic-mautic-1 chown -R apache:apache /var/www/
    - name: Root path check
      run: |
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/apache2/httpd.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/apache2/httpd.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  
  Apache-php7-mautic-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image apache, php 7.4 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "7.4"
        BACK_END: apache
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www/
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic_mautic_1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic_mautic_1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic_mautic_1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic_mautic_1 composer
    - name: Folder check
      run:  docker exec mautic_mautic_1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic_mautic_1 chown -R apache:apache /var/www/
    - name: Root path check
      run: |
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/apache2/httpd.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic_mautic_1 chown -R nobody:nobody /var/www/
        docker exec mautic_mautic_1 ls -la
        docker exec mautic_mautic_1 cat /etc/apache2/httpd.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic
  Apache-php7-mautic-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image apache, php 7.4 and mautic
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "7.4"
        BACK_END: apache
        XDEBUG: true
        DISPLAY_PHPERROR: true
        SERVER_ROOT:  /var/www
        APP_CODE_PATH_HOST: /tmp/mautic
        DB_NAME:  test
        DB_USER:  admin
        DB_PASSWORD:  password
        DATA_PATH_HOST: /tmp/db
    - name: PHP version check
      run:  docker exec mautic-mautic-1 php -v
    - name: Mongodb driver check
      run:  docker exec mautic-mautic-1 php -m | grep mongo
    - name: Mysql Driver check
      run: docker exec mautic-mautic-1 php -m | grep mysqli
    - name: Composer test
      run: docker exec mautic-mautic-1 composer
    - name: Folder check
      run:  docker exec mautic-mautic-1 ls -la /app/
    - name: Application Install
      run:  |
        docker exec mautic-mautic-1 chown -R apache:apache /var/www/
    - name: Root path check
      run: |
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/apache2/httpd.conf
    - name: Durpal application test
      run:  |
        sleep 30s
        docker exec mautic-mautic-1 chown -R nobody:nobody /var/www/
        docker exec mautic-mautic-1 ls -la
        docker exec mautic-mautic-1 cat /etc/apache2/httpd.conf
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5647/index.php/installer)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/db
        sudo rm -rf /tmp/mautic